# Generated by Django 4.1.4 on 2023-01-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler_Coches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alta_Gama', models.CharField(max_length=30)),
                ('Media_Gama', models.CharField(max_length=30)),
                ('Compacto', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=40)),
                ('ciudad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hoteles', models.CharField(max_length=30)),
                ('Apartamentos', models.CharField(max_length=30)),
                ('Casas', models.EmailField(max_length=254)),
            ],
        ),
    ]
