# Generated by Django 4.1.4 on 2023-01-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler_coches',
            name='Compacto',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='destino',
            name='ciudad',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hospedaje',
            name='Casas',
            field=models.IntegerField(),
        ),
    ]
