# Generated by Django 4.1.4 on 2023-01-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega3', '0002_alter_alquiler_coches_compacto_alter_destino_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospedaje',
            old_name='Casas',
            new_name='Personas',
        ),
        migrations.RenameField(
            model_name='hospedaje',
            old_name='Apartamentos',
            new_name='Zona',
        ),
    ]
